name: 'Mach Composer Plan'
description: 'Run mach-composer plan and update PR'
inputs:
  filename:
    description: 'name of the mach-composer config file'
    required: true
    default: 'main.yml'
  github-token:
    description: 'Your github token'
    required: true
  working-directory:
    description: 'The working directory to run mach-composer in'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Run MACH Composer plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mach-composer plan -f ${{ inputs.filename }}
      id: plan

    - name: Show MACH Composer plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mach-composer show-plan -f ${{ inputs.filename }} --no-color | grep -v "^::debug::" >${GITHUB_WORKSPACE}/plan.out
      id: show-plan

    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event.pull_request.merged != true
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('plan.out', 'utf8');
          const planOutput = plan.length > 65000 ? plan.substring(0, 65000) : plan;
          const truncatedMessage = plan.length > 65000 ? "Output is too long and has been truncated" : "";
          const output = `#### MACH composer plan 📖

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${planOutput}
          \`\`\`

          </details>
          ${truncatedMessage}

          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
